### PR TITLE
Mockups

### PR DESCRIPTION
**Pull request by rhlsthrm**
Initial set of mockups ready for review.

### CODE REVIEW

**Review by Alonski — CHANGES_REQUESTED** [review]
About login page and create account:
I don't think we need these pages.
We should be using the Ethereum address as the user identifier and not a username/password combo.
A user should be able to open up a Supportee page and in seconds support them without creating an account.

If the user decides however that he does want to edit his account settings such as: Name, Biography etc he can choose to do so in a Settings page that looks like the Create Account page that you built.
The Ethereum Address should be filled in already.

About the Start Page / Home page:
I think it should default to a mix of the Explore Page with a short explanation about what CoinPanion is about.

Dashboard:
Looks pretty cool 🥇 
Maybe needs a history list of recent subscribers with how much they subscribed for?

About support:
Looks good. I believe Status, MM etc will take care of the exact implementation for how to Send and Confirm but looks nice.

Searching:
Looks good as well

All in all great job!
This will really help us drive the initial development!

**Comment by imbaniac** [comment]
@Alonski If we'll use Eth address as login method, will I able to login to your account if I'll have your address on hands?

**Comment by Alonski** [comment]
@imbaniac You need to be connected with this Eth Address.
Either VIA MetaMask, Status, Mist etc

**Comment by Josephrp** [comment]
Priv key is required for auth usually ...

**Comment by rhlsthrm** [comment]
Yes, I am still confused about the login method as well in terms of public Eth address and private key.

**Pull request merged**
